# Cada uma dessas linhas serve para ensinar o Spring Boot
# conversar com o seu banco de dados PostgreSQL usando Hibernate/JPA
# (que é a tecnologia que transforma código Java em tabelas).

# Define o nome da sua aplicação. 
# É útil para logs e se você usar microsserviços no futuro.
spring.application.name=sisRec

# URL de conexão: altera o 'localhost:5432' se o seu banco usar outra porta, e 'siccsrDB' é o nome do seu banco
spring.datasource.url=jdbc:postgresql://localhost:5432/siccsrDB
spring.datasource.username=postgres
spring.datasource.password=12345678

# Configurações do Hibernate / JPA
# Essa é uma das mais importantes. 
# O update diz ao Java para criar ou atualizar as tabelas no banco 
# automaticamente sempre que você criar ou mudar uma classe no código. 
# Você não precisará escrever comandos SQL como CREATE TABLE.
spring.jpa.hibernate.ddl-auto=update

# Manda o Spring mostrar no terminal todo comando SQL que ele executar 
# por debaixo dos panos.
# É excelente para entender o que está acontecendo e achar erros.
spring.jpa.show-sql=true

# Organiza o SQL que aparece no terminal de forma bonita e legível 
# (com quebras de linha), em vez de uma linha gigante confusa.
spring.jpa.properties.hibernate.format_sql=true

# Informa ao Hibernate o "sotaque" do banco de dados. 
# Como cada banco (MySQL, Oracle, Postgres) 
# tem pequenas variações de comandos, essa linha garante que o 
# Spring use a linguagem exata do PostgreSQL.
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Força o Hibernate a gerar TODOS os nomes de tabelas e colunas em letras minúsculas e com sublinhados
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.hibernate.naming.implicit-strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl

# Mostra o erro real do banco detalhado no console do VS Code
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.format_sql=true

# Mude de update para none para o Hibernate não tentar alterar suas tabelas físicas
spring.jpa.hibernate.ddl-auto=none